package launcher

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"claude-profile-manager/internal/profile"
	"claude-profile-manager/internal/shellwords"
)

// Shell names accepted by Snippet.
const (
	ShellPOSIX      = "posix"
	ShellPowerShell = "powershell"
	ShellCmd        = "cmd"
)

// DefaultShell is the most likely shell for the current OS.
func DefaultShell() string {
	if runtime.GOOS == "windows" {
		return ShellPowerShell
	}
	return ShellPOSIX
}

// Title is the window title used for a profile's terminal.
func Title(p *profile.Profile) string { return "Claude · " + p.Name }

// Snippet renders a copy-pasteable command that starts Claude Code for p in
// the given shell, from the current directory.
func Snippet(p *profile.Profile, cli, shell string) (string, error) {
	args, err := p.Args()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	switch shell {
	case ShellPowerShell:
		for _, v := range Overrides(p) {
			if v.Unset {
				fmt.Fprintf(&b, "Remove-Item Env:%s -ErrorAction SilentlyContinue; ", v.Key)
			} else {
				fmt.Fprintf(&b, "$env:%s = %s; ", v.Key, shellwords.QuotePowerShell(v.Value))
			}
		}
		b.WriteString("& " + shellwords.QuotePowerShell(cli))
		for _, a := range args {
			b.WriteString(" " + shellwords.QuotePowerShell(a))
		}
	case ShellCmd:
		for _, v := range Overrides(p) {
			fmt.Fprintf(&b, "set \"%s=%s\" && ", v.Key, strings.ReplaceAll(v.Value, "%", "%%"))
		}
		b.WriteString(shellwords.QuoteCmd(cli))
		for _, a := range args {
			b.WriteString(" " + shellwords.QuoteCmd(a))
		}
	default:
		var unset []string
		for _, v := range Overrides(p) {
			if v.Unset {
				unset = append(unset, v.Key)
			}
		}
		if len(unset) > 0 {
			b.WriteString("env")
			for _, k := range unset {
				b.WriteString(" -u " + k)
			}
		}
		for _, v := range Overrides(p) {
			if !v.Unset {
				if b.Len() > 0 {
					b.WriteString(" ")
				}
				b.WriteString(v.Key + "=" + shellwords.QuotePOSIX(v.Value))
			}
		}
		b.WriteString(" " + shellwords.QuotePOSIX(cli))
		for _, a := range args {
			b.WriteString(" " + shellwords.QuotePOSIX(a))
		}
	}
	return b.String(), nil
}

// WriteScript generates the launch script for p in its data directory and
// returns its path. The script sets the profile environment explicitly
// (rather than relying on inheritance, which terminals such as Windows
// Terminal and macOS Terminal.app do not guarantee), changes into dir, runs
// Claude Code with extra, then leaves an interactive shell open that still
// carries the profile environment.
func WriteScript(p *profile.Profile, cli, dir string, extra []string) (string, error) {
	args, err := p.Args()
	if err != nil {
		return "", err
	}
	args = append(args, extra...)
	if dir == "" {
		dir = p.StartDir()
	}
	if err := os.MkdirAll(p.Dir(), 0o700); err != nil {
		return "", err
	}

	var name, body string
	switch runtime.GOOS {
	case "windows":
		name, body = "launch.cmd", cmdScript(p, cli, dir, args)
	case "darwin":
		// .command files open (and run) in Terminal/iTerm via `open -a`.
		name, body = "launch.command", posixScript(p, cli, dir, args)
	default:
		name, body = "launch.sh", posixScript(p, cli, dir, args)
	}
	path := filepath.Join(p.Dir(), name)
	if err := os.WriteFile(path, []byte(body), 0o700); err != nil {
		return "", err
	}
	if runtime.GOOS == "windows" {
		ps := filepath.Join(p.Dir(), "launch.ps1")
		if err := os.WriteFile(ps, []byte(ps1Script(p, cli, dir, args)), 0o600); err != nil {
			return "", err
		}
	}
	return path, nil
}

// PowerShellScriptPath is the companion script WriteScript emits on Windows.
func PowerShellScriptPath(p *profile.Profile) string { return filepath.Join(p.Dir(), "launch.ps1") }

func posixScript(p *profile.Profile, cli, dir string, args []string) string {
	q := shellwords.QuotePOSIX
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	fmt.Fprintf(&b, "# Generated by Claude Profile Manager for profile %q — regenerated on every launch.\n", p.Name)
	fmt.Fprintf(&b, "printf '\\033]0;%%s\\007' %s\n", q(Title(p)))
	for _, v := range Overrides(p) {
		if v.Unset {
			fmt.Fprintf(&b, "unset %s\n", v.Key)
		} else {
			fmt.Fprintf(&b, "export %s=%s\n", v.Key, q(v.Value))
		}
	}
	fmt.Fprintf(&b, "cd %s || exit 1\n", q(dir))
	b.WriteString(q(cli))
	for _, a := range args {
		b.WriteString(" " + q(a))
	}
	b.WriteString(" \"$@\"\n")
	b.WriteString("echo\n")
	fmt.Fprintf(&b, "echo %s\n", q("Claude Code exited. This shell keeps the \""+p.Name+"\" profile environment; type exit to close."))
	b.WriteString("exec \"${SHELL:-/bin/sh}\" -i\n")
	return b.String()
}

func cmdScript(p *profile.Profile, cli, dir string, args []string) string {
	esc := func(s string) string { return strings.ReplaceAll(s, "%", "%%") }
	var b strings.Builder
	b.WriteString("@echo off\r\n")
	b.WriteString("chcp 65001 >nul\r\n")
	fmt.Fprintf(&b, "rem Generated by Claude Profile Manager for profile \"%s\" - regenerated on every launch.\r\n", esc(p.Name))
	fmt.Fprintf(&b, "title %s\r\n", esc(strings.NewReplacer("&", "^&", "|", "^|", "<", "^<", ">", "^>").Replace(Title(p))))
	for _, v := range Overrides(p) {
		if v.Unset {
			fmt.Fprintf(&b, "set \"%s=\"\r\n", v.Key)
		} else {
			fmt.Fprintf(&b, "set \"%s=%s\"\r\n", v.Key, esc(v.Value))
		}
	}
	fmt.Fprintf(&b, "cd /d %s || exit /b 1\r\n", shellwords.QuoteCmd(dir))
	// `call` so control returns here when claude is an npm .cmd shim.
	b.WriteString("call " + shellwords.QuoteCmd(cli))
	for _, a := range args {
		b.WriteString(" " + shellwords.QuoteCmd(a))
	}
	b.WriteString(" %*\r\n")
	b.WriteString("echo.\r\n")
	fmt.Fprintf(&b, "echo Claude Code exited. This window keeps the \"%s\" profile environment.\r\n", esc(p.Name))
	return b.String()
}

func ps1Script(p *profile.Profile, cli, dir string, args []string) string {
	q := shellwords.QuotePowerShell
	var b strings.Builder
	// UTF-8 BOM so Windows PowerShell 5.1 reads non-ASCII paths correctly.
	b.WriteString("\xEF\xBB\xBF")
	fmt.Fprintf(&b, "# Generated by Claude Profile Manager for profile %q - regenerated on every launch.\r\n", p.Name)
	fmt.Fprintf(&b, "$Host.UI.RawUI.WindowTitle = %s\r\n", q(Title(p)))
	for _, v := range Overrides(p) {
		if v.Unset {
			fmt.Fprintf(&b, "Remove-Item Env:%s -ErrorAction SilentlyContinue\r\n", v.Key)
		} else {
			fmt.Fprintf(&b, "$env:%s = %s\r\n", v.Key, q(v.Value))
		}
	}
	fmt.Fprintf(&b, "Set-Location -LiteralPath %s\r\n", q(dir))
	b.WriteString("& " + q(cli))
	for _, a := range args {
		b.WriteString(" " + q(a))
	}
	b.WriteString(" @args\r\n")
	fmt.Fprintf(&b, "Write-Host \"`nClaude Code exited. This window keeps the %s profile environment.\"\r\n",
		strings.ReplaceAll(strings.ReplaceAll(p.Name, "`", "``"), "\"", "`\""))
	return b.String()
}
